package com.example.gangapackagesolution.models.Quotation

import com.example.gangapackagesolution.models.itemsParticaular.itemParticulars
import kotlinx.serialization.Serializable


data class Quotation(
    val address: String,
    val address2: String,
    val advancePaid: String,
    val areAnyRestrictionLoading: String,
    val carBikeTpt: String,
    val city: String,
    val city2: String,
    val companyName: String,
    val country: String,
    val country2: String,
    val date: String,
    val declarationValue: String,
    val declarationValue1: String,
    val discount: String,
    val doesAnySpecialNeedsOrConcerns: String,
    val easyAccessForLoading: String,
    val email: String,
    val freightCharge: String,
    val gst: String,
    val gstIn: String,
    val gstType: String,
    val gstperc: String,
    val gstperc1: String,
    val id: Int,
    val insuranceCharge: String,
    val insuranceCharge1: String,
    val insuranceType: String,
    val insuranceType1: String,
    val list: List<itemParticulars>,
    val loadingCharge: String,
    val loadingChargeType: String,
    val markAsPAid: Boolean,
    val miscelaneousCharge: String,
    val movingType: String,
    val octroiGreenTAx: String,
    val otherCharge: String,
    val packagingCharge: String,
    val packagingMaterialType: String,
    val packingChargeType: String,
    val packingDate: String,
    val packingMaterialCharge: String,
    val partyName: String,
    val phoneNumber: String,
    val pinCode: String,
    val pinCode2: String,
    val qtdate: String,
    val remark: String,
    val shiftingDate: String,
    val shouldAnyItemGotDown: String,
    val stCharge: String,
    val state: String,
    val state2: String,
    val status: String,
    val storageCharge: String,
    val subchargeType: String,
    val subcharges: String,
    val unloadingCharge: String,
    val unloadingChargeType: String,
    val unpackingCharge: String,
    val unpackingChargeType: String,
    val total: String
)